# Generated by Django 4.2.3 on 2023-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
