# Generated by Django 4.2.3 on 2023-07-23 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commands", "0002_alter_command_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="created_at",
            new_name="updated_at",
        ),
    ]
