# Generated by Django 4.2.3 on 2023-07-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrammessage",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
